# Generated by Django 2.0 on 2019-05-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('rut', models.CharField(max_length=45)),
                ('telefono1', models.IntegerField()),
                ('telefono2', models.IntegerField()),
                ('direccion', models.CharField(max_length=45)),
                ('fecha_compra', models.DateField()),
                ('modo_de_pago', models.CharField(max_length=45)),
                ('tipo_de_entrega', models.CharField(max_length=45)),
                ('comentario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('fecha_llegada', models.DateField()),
                ('precio_llegada', models.IntegerField()),
                ('descripcion', models.CharField(max_length=45)),
                ('fecha_venta', models.DateField()),
                ('precio_venta', models.IntegerField()),
                ('proveedor', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('rut', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('insumo', models.CharField(max_length=45)),
                ('cantidad_insumo', models.IntegerField()),
            ],
        ),
    ]
